import datetime
import time
import os
import builtins
import lib_of_digitsHW6

os.system('clear')

while True:
    current_sys_time = datetime.datetime.today().strftime("%H:%M:%S") #take current time - HH:MM:SS
    stamp = str(list(current_sys_time))
    a = stamp
    b = stamp
    c = stamp
    d = stamp
    e = stamp
    f = stamp
    g = stamp
    h = stamp
    i = stamp
    j = stamp
    k = stamp
    l = stamp
    m = stamp
    n = stamp
    o = stamp
    p = stamp

    a = a.replace("0",lib_of_digitsHW6.z0_0)
    a = a.replace("1",lib_of_digitsHW6.z1_0) 
    a = a.replace("2",lib_of_digitsHW6.z2_0)
    a = a.replace("3",lib_of_digitsHW6.z3_0)
    a = a.replace("4",lib_of_digitsHW6.z4_0)
    a = a.replace("5",lib_of_digitsHW6.z5_0)
    a = a.replace("6",lib_of_digitsHW6.z6_0)
    a = a.replace("7",lib_of_digitsHW6.z7_0)
    a = a.replace("8",lib_of_digitsHW6.z8_0)
    a = a.replace("9",lib_of_digitsHW6.z9_0)
    a = a.replace(":",u"\u2B1B")
    a = a.replace("[","")
    a = a.replace("]","")
    a = a.replace(",","")
    a = a.replace("'","")
    a = a.replace(" ","")
    print(a)
    
    
    b = b.replace("0",lib_of_digitsHW6.z0_1)
    b = b.replace("1",lib_of_digitsHW6.z1_1) 
    b = b.replace("2",lib_of_digitsHW6.z2_1)
    b = b.replace("3",lib_of_digitsHW6.z3_1)
    b = b.replace("4",lib_of_digitsHW6.z4_1)
    b = b.replace("5",lib_of_digitsHW6.z5_1)
    b = b.replace("6",lib_of_digitsHW6.z6_1)
    b = b.replace("7",lib_of_digitsHW6.z7_1)
    b = b.replace("8",lib_of_digitsHW6.z8_1)
    b = b.replace("9",lib_of_digitsHW6.z9_1)
    b = b.replace(":",u"\u2B1B")
    b = b.replace("[","")
    b = b.replace("]","")
    b = b.replace(",","")
    b = b.replace("'","")
    b = b.replace(" ","")
    print(b)

    c = c.replace("0",lib_of_digitsHW6.z0_2)
    c = c.replace("1",lib_of_digitsHW6.z1_2) 
    c = c.replace("2",lib_of_digitsHW6.z2_2)
    c = c.replace("3",lib_of_digitsHW6.z3_2)
    c = c.replace("4",lib_of_digitsHW6.z4_2)
    c = c.replace("5",lib_of_digitsHW6.z5_2)
    c = c.replace("6",lib_of_digitsHW6.z6_2)
    c = c.replace("7",lib_of_digitsHW6.z7_2)
    c = c.replace("8",lib_of_digitsHW6.z8_2)
    c = c.replace("9",lib_of_digitsHW6.z9_2)
    c = c.replace(":",u"\u2B1C")
    c = c.replace("[","")
    c = c.replace("]","")
    c = c.replace(",","")
    c = c.replace("'","")
    c = c.replace(" ","")
    print(c)

    d = d.replace("0",lib_of_digitsHW6.z0_3)
    d = d.replace("1",lib_of_digitsHW6.z1_3)
    d = d.replace("2",lib_of_digitsHW6.z2_3)
    d = d.replace("3",lib_of_digitsHW6.z3_3)
    d = d.replace("4",lib_of_digitsHW6.z4_3)
    d = d.replace("5",lib_of_digitsHW6.z5_3)
    d = d.replace("6",lib_of_digitsHW6.z6_3)
    d = d.replace("7",lib_of_digitsHW6.z7_3)
    d = d.replace("8",lib_of_digitsHW6.z8_3)
    d = d.replace("9",lib_of_digitsHW6.z9_3)
    d = d.replace(":",u"\u2B1B")
    d = d.replace("[","")
    d = d.replace("]","")
    d = d.replace(",","")
    d = d.replace("'","")
    d = d.replace(" ","")
    print(d)

    e = e.replace("0",lib_of_digitsHW6.z0_4)
    e = e.replace("1",lib_of_digitsHW6.z1_4)
    e = e.replace("2",lib_of_digitsHW6.z2_4)
    e = e.replace("3",lib_of_digitsHW6.z3_4)
    e = e.replace("4",lib_of_digitsHW6.z4_4)
    e = e.replace("5",lib_of_digitsHW6.z5_4)
    e = e.replace("6",lib_of_digitsHW6.z6_4)
    e = e.replace("7",lib_of_digitsHW6.z7_4)
    e = e.replace("8",lib_of_digitsHW6.z8_4)
    e = e.replace("9",lib_of_digitsHW6.z9_4)
    e = e.replace(":",u"\u2B1B")
    e = e.replace("[","")
    e = e.replace("]","")
    e = e.replace(",","")
    e = e.replace("'","")
    e = e.replace(" ","")
    print(e)

    f = f.replace("0",lib_of_digitsHW6.z0_5)
    f = f.replace("1",lib_of_digitsHW6.z1_5)
    f = f.replace("2",lib_of_digitsHW6.z2_5)
    f = f.replace("3",lib_of_digitsHW6.z3_5)
    f = f.replace("4",lib_of_digitsHW6.z4_5)
    f = f.replace("5",lib_of_digitsHW6.z5_5)
    f = f.replace("6",lib_of_digitsHW6.z6_5)
    f = f.replace("7",lib_of_digitsHW6.z7_5)
    f = f.replace("8",lib_of_digitsHW6.z8_5)
    f = f.replace("9",lib_of_digitsHW6.z9_5)
    f = f.replace(":",u"\u2B1C")
    f = f.replace("[","")
    f = f.replace("]","")
    f = f.replace(",","")
    f = f.replace("'","")
    f = f.replace(" ","")
    print(f)

    g = g.replace("0",lib_of_digitsHW6.z0_6)
    g = g.replace("1",lib_of_digitsHW6.z1_6)
    g = g.replace("2",lib_of_digitsHW6.z2_6)
    g = g.replace("3",lib_of_digitsHW6.z3_6)
    g = g.replace("4",lib_of_digitsHW6.z4_6)
    g = g.replace("5",lib_of_digitsHW6.z5_6)
    g = g.replace("6",lib_of_digitsHW6.z6_6)
    g = g.replace("7",lib_of_digitsHW6.z7_6)
    g = g.replace("8",lib_of_digitsHW6.z8_6)
    g = g.replace("9",lib_of_digitsHW6.z9_6)
    g = g.replace(":",u"\u2B1B")
    g = g.replace("[","")
    g = g.replace("]","")
    g = g.replace(",","")
    g = g.replace("'","")
    g = g.replace(" ","")
    print(g)

    h = h.replace("0",lib_of_digitsHW6.z0_7)
    h = h.replace("1",lib_of_digitsHW6.z1_7)
    h = h.replace("2",lib_of_digitsHW6.z2_7)
    h = h.replace("3",lib_of_digitsHW6.z3_7)
    h = h.replace("4",lib_of_digitsHW6.z4_7)
    h = h.replace("5",lib_of_digitsHW6.z5_7)
    h = h.replace("6",lib_of_digitsHW6.z6_7)
    h = h.replace("7",lib_of_digitsHW6.z7_7)
    h = h.replace("8",lib_of_digitsHW6.z8_7)
    h = h.replace("9",lib_of_digitsHW6.z9_7)
    h = h.replace(":",u"\u2B1B")
    h = h.replace("[","")
    h = h.replace("]","")
    h = h.replace(",","")
    h = h.replace("'","")
    h = h.replace(" ","")
    print(h)

    os.system('clear')
    #second cycle
    
    i = i.replace("0",lib_of_digitsHW6.z0_0)
    i = i.replace("1",lib_of_digitsHW6.z1_0) 
    i = i.replace("2",lib_of_digitsHW6.z2_0)
    i = i.replace("3",lib_of_digitsHW6.z3_0)
    i = i.replace("4",lib_of_digitsHW6.z4_0)
    i = i.replace("5",lib_of_digitsHW6.z5_0)
    i = i.replace("6",lib_of_digitsHW6.z6_0)
    i = i.replace("7",lib_of_digitsHW6.z7_0)
    i = i.replace("8",lib_of_digitsHW6.z8_0)
    i = i.replace("9",lib_of_digitsHW6.z9_0)
    i = i.replace(":",u"\u2B1B")
    i = i.replace("[","")
    i = i.replace("]","")
    i = i.replace(",","")
    i = i.replace("'","")
    i = i.replace(" ","")
    print(i)
    
    
    j = j.replace("0",lib_of_digitsHW6.z0_1)
    j = j.replace("1",lib_of_digitsHW6.z1_1) 
    j = j.replace("2",lib_of_digitsHW6.z2_1)
    j = j.replace("3",lib_of_digitsHW6.z3_1)
    j = j.replace("4",lib_of_digitsHW6.z4_1)
    j = j.replace("5",lib_of_digitsHW6.z5_1)
    j = j.replace("6",lib_of_digitsHW6.z6_1)
    j = j.replace("7",lib_of_digitsHW6.z7_1)
    j = j.replace("8",lib_of_digitsHW6.z8_1)
    j = j.replace("9",lib_of_digitsHW6.z9_1)
    j = j.replace(":",u"\u2B1C")
    j = j.replace("[","")
    j = j.replace("]","")
    j = j.replace(",","")
    j = j.replace("'","")
    j = j.replace(" ","")
    print(j)

    k = k.replace("0",lib_of_digitsHW6.z0_2)
    k = k.replace("1",lib_of_digitsHW6.z1_2) 
    k = k.replace("2",lib_of_digitsHW6.z2_2)
    k = k.replace("3",lib_of_digitsHW6.z3_2)
    k = k.replace("4",lib_of_digitsHW6.z4_2)
    k = k.replace("5",lib_of_digitsHW6.z5_2)
    k = k.replace("6",lib_of_digitsHW6.z6_2)
    k = k.replace("7",lib_of_digitsHW6.z7_2)
    k = k.replace("8",lib_of_digitsHW6.z8_2)
    k = k.replace("9",lib_of_digitsHW6.z9_2)
    k = k.replace(":",u"\u2B1B")
    k = k.replace("[","")
    k = k.replace("]","")
    k = k.replace(",","")
    k = k.replace("'","")
    k = k.replace(" ","")
    print(k)

    l = l.replace("0",lib_of_digitsHW6.z0_3)
    l = l.replace("1",lib_of_digitsHW6.z1_3)
    l = l.replace("2",lib_of_digitsHW6.z2_3)
    l = l.replace("3",lib_of_digitsHW6.z3_3)
    l = l.replace("4",lib_of_digitsHW6.z4_3)
    l = l.replace("5",lib_of_digitsHW6.z5_3)
    l = l.replace("6",lib_of_digitsHW6.z6_3)
    l = l.replace("7",lib_of_digitsHW6.z7_3)
    l = l.replace("8",lib_of_digitsHW6.z8_3)
    l = l.replace("9",lib_of_digitsHW6.z9_3)
    l = l.replace(":",u"\u2B1B")
    l = l.replace("[","")
    l = l.replace("]","")
    l = l.replace(",","")
    l = l.replace("'","")
    l = l.replace(" ","")
    print(l)

    m = m.replace("0",lib_of_digitsHW6.z0_4)
    m = m.replace("1",lib_of_digitsHW6.z1_4)
    m = m.replace("2",lib_of_digitsHW6.z2_4)
    m = m.replace("3",lib_of_digitsHW6.z3_4)
    m = m.replace("4",lib_of_digitsHW6.z4_4)
    m = m.replace("5",lib_of_digitsHW6.z5_4)
    m = m.replace("6",lib_of_digitsHW6.z6_4)
    m = m.replace("7",lib_of_digitsHW6.z7_4)
    m = m.replace("8",lib_of_digitsHW6.z8_4)
    m = m.replace("9",lib_of_digitsHW6.z9_4)
    m = m.replace(":",u"\u2B1C")
    m = m.replace("[","")
    m = m.replace("]","")
    m = m.replace(",","")
    m = m.replace("'","")
    m = m.replace(" ","")
    print(m)

    n = n.replace("0",lib_of_digitsHW6.z0_5)
    n = n.replace("1",lib_of_digitsHW6.z1_5)
    n = n.replace("2",lib_of_digitsHW6.z2_5)
    n = n.replace("3",lib_of_digitsHW6.z3_5)
    n = n.replace("4",lib_of_digitsHW6.z4_5)
    n = n.replace("5",lib_of_digitsHW6.z5_5)
    n = n.replace("6",lib_of_digitsHW6.z6_5)
    n = n.replace("7",lib_of_digitsHW6.z7_5)
    n = n.replace("8",lib_of_digitsHW6.z8_5)
    n = n.replace("9",lib_of_digitsHW6.z9_5)
    n = n.replace(":",u"\u2B1B")
    n = n.replace("[","")
    n = n.replace("]","")
    n = n.replace(",","")
    n = n.replace("'","")
    n = n.replace(" ","")
    print(n)

    o = o.replace("0",lib_of_digitsHW6.z0_6)
    o = o.replace("1",lib_of_digitsHW6.z1_6)
    o = o.replace("2",lib_of_digitsHW6.z2_6)
    o = o.replace("3",lib_of_digitsHW6.z3_6)
    o = o.replace("4",lib_of_digitsHW6.z4_6)
    o = o.replace("5",lib_of_digitsHW6.z5_6)
    o = o.replace("6",lib_of_digitsHW6.z6_6)
    o = o.replace("7",lib_of_digitsHW6.z7_6)
    o = o.replace("8",lib_of_digitsHW6.z8_6)
    o = o.replace("9",lib_of_digitsHW6.z9_6)
    o = o.replace(":",u"\u2B1B")
    o = o.replace("[","")
    o = o.replace("]","")
    o = o.replace(",","")
    o = o.replace("'","")
    o = o.replace(" ","")
    print(o)

    p = p.replace("0",lib_of_digitsHW6.z0_7)
    p = p.replace("1",lib_of_digitsHW6.z1_7)
    p = p.replace("2",lib_of_digitsHW6.z2_7)
    p = p.replace("3",lib_of_digitsHW6.z3_7)
    p = p.replace("4",lib_of_digitsHW6.z4_7)
    p = p.replace("5",lib_of_digitsHW6.z5_7)
    p = p.replace("6",lib_of_digitsHW6.z6_7)
    p = p.replace("7",lib_of_digitsHW6.z7_7)
    p = p.replace("8",lib_of_digitsHW6.z8_7)
    p = p.replace("9",lib_of_digitsHW6.z9_7)
    p = p.replace(":",u"\u2B1B")
    p = p.replace("[","")
    p = p.replace("]","")
    p = p.replace(",","")
    p = p.replace("'","")
    p = p.replace(" ","")
    print(p)

    time.sleep(0.2)
    os.system('clear')